TYPO3:
  Flow:
    object:
      excludeClasses:
       'kriswallsmith.assetic' : ['.*']
       'symfony.process' : ['Symfony\\Component\\Process\\Tests\\.*']
       'twig.twig' : ['.*']
       'oyejorge.less.php' : ['.*']